name: 'install-merlin32-action'
description: 'Github Action to set up Merlin32 Assembler'
author: 'Dagen Brock'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'link'
  color: 'blue'
